env:
  browser: true
  commonjs: true
  es6: true
  node: true
  worker: true
  jest: true
plugins:
  - 'promise'
extends: 
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:promise/recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
globals:
  page: true
  browser: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single 
  semi:
    - error
    - always
  no-console:
    - warn
