env:
  browser: true
  commonjs: true
  es6: true
  node: true
  worker: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017 
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single 
  semi:
    - error
    - always
  no-console:
    - warn
