language: node_js
node_js:
 - '10.1.0'
sudo: disabled

cache: 
  directories:
    - "node_modules"


install:
  - npm install

before_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./node_modules/.bin/precise-commits --whitelist="./**/!(*.json)" --check-only --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master