language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
 - 'node'
 - 'lts/*'
sudo: false

cache: 
  directories:
    # cache the larger node_modules we use throughout the tree 
    # - "node_modules"
    # - "src/editor/node_modules"
    # - "src/website/node_modules"
    # cache the bios, linux binary images
    - "dist/terminal/bin"

script:
  - npm run travis

before_deploy:
  # Do the entire build
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: dist
  on:
    branch: master
    node: 'lts/*'

