language: node_js
node_js:
 - '10.1.0'
sudo: disabled

cache: 
  directories:
    - "node_modules"

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./node_modules/.bin/precise-commits --whitelist="./**/!(*.json)" --check-only --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'

install:
  - npm install
