language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
 - 'node'
 - 'lts/*'
sudo: false

cache: 
  directories:
    - $HOME/.npm

script:
  - npm run travis

before_deploy:
  # Do the entire build
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAGES  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: dist
  on:
    branch: master
    node: 'lts/*'
