/*
 * Copyright (c) 2012 Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

define({

    "GENERIC_ERROR": "(хатогӣ {0})",
    "NOT_FOUND_ERR": "Файли /directory дарёфт нашуд.",
    "NOT_READABLE_ERR": "Файли /directory - ро хондан номумкин аст.",
    "EXCEEDS_MAX_FILE_SIZE": "файлҳое ки андозаашон {0} MB мебошанд, дар {APP_NAME} кушода намешаванд.",
    "FILE_EXISTS_ERR": "Файл ё ки каталог аллакай мавҷуд аст.",
    "FILE": "файл",
    "FILE_TITLE": "Файл",
    "DIRECTORY": "даструламал",
    "DIRECTORY_TITLE": "Даструламал",
    "DIRECTORY_NAMES_LEDE": "Номҳои даструламал",
    "FILENAMES_LEDE": "Номҳои файлҳо",
    "FILENAME": "Номи файлҳо",
    "DIRECTORY_NAME": "Номи даструламал",
    "OPEN_DIALOG_ERROR": "Ҳангоми кушодани файл хатогӣ ба амал омад. (хатогӣ {0})",
    "READ_DIRECTORY_ENTRIES_ERROR": "ҳангоми хондани мазмуни феҳристи <span синфи = 'муколамаи-номи файли'> {0} </ span> хатогӣ пайдо шуд. (Хато {1})",
    "ERROR_OPENING_FILE_TITLE": "Хатогӣ Ҳангоми кушодани файл",
    "ERROR_OPENING_FILE": "Ҳангоми кушодани файл хатогӣ рӯй дод <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_OPENING_FILES": "Ҳангоми кӯшиши кушодани файлҳои зерин хатогӣ рӯй дод:",
    "ERROR_SAVING_FILE_TITLE": "Хатогии кушодани файл",
    "ERROR_SAVING_FILE": "Ҳангоми кӯшиши кушодани файл хатогӣ рӯй дод<span class='dialog-filename'>{0}</span>.{1}",
    "ERROR_RENAMING_FILE_TITLE": "Хатогӣ ҳангоми азнав номгузории файл",
    "ERROR_RENAMING_DIRECTORY_TITLE": "Хатогии азнав номгузории каталог",
    "ERROR_RENAMING_FILE": "Хангоми кӯшиши аз нав номгузории файл хатогӣ рӯй дод<span class='dialog-filename'>{0}</span>.{1}",
    "ERROR_RENAMING_DIRECTORY": "Хангоми кӯшиши аз нав номгузаронии файл хатогӣ рӯй дод<span class='dialog-filename'>{0}</span>.{1}",
    "ERROR_DELETING_FILE_TITLE": "Хатогӣ Ҳангоми Тозакунии Файл ",
    "ERROR_DELETING_DIRECTORY_TITLE": "Хатогӣ ҳангоми тоза кардани каталог",
    "ERROR_DELETING_FILE": "Хангоми тозакунии файл хатогӣ рӯй дод<span class='dialog-filename'>{0}</span>.{1}",
    "ERROR_DELETING_DIRECTORY": "Хангоми кӯшиши тозакунии каталог хатогӣ рӯй дод<span class='dialog-filename'>{0}</span>.{1}",
    "INVALID_FILENAME_TITLE": "Номи Файл Нодуруст Аст",
    "INVALID_DIRNAME_TITLE": "Номи Даструламал Нодуруст Аст",
    "INVALID_FILENAME_MESSAGE": "Номи файл наметавонад  бо нуқта тамомо шавад ва ё аз символҳои зерин иборат бошад:<code class='emphasized'>{1}</code>",
    "INVALID_DIRNAME_MESSAGE": "Номи даструламал наметавонад  бо нуқта тамомо шавад ва ё аз символҳои зерин иборат бошад:<code class='emphasized'>{1}</code>",
    "ENTRY_WITH_SAME_NAME_EXISTS": "Файл, ё ки даструламал бо номи <span class='dialog-filename'>{0}</span>аллакай мавҷуд аст.",
    "ERROR_CREATING_FILE_TITLE": "Хатогӣ Ҳангоми Сохтани Файл",
    "ERROR_CREATING_DIRECTORY_TITLE": "Хатогӣ Ҳангоми Сохтани Даструламал",
    "ERROR_CREATING_FILE": "Ҳангоми кӯшиши сохтани файл хатогӣ рӯй дод<span class='dialog-filename'>{1}</span>.{2}",
    "ERROR_CREATING_DIRECTORY": "Ҳангоми кӯшиши сохтани каталог хатогӣ рӯй дод<span class='dialog-filename'>{1}</span>.{2}",
    "ERROR_MAX_FILES_TITLE": "Хатогии  Индексиронии Файл ",
    "EXT_MODIFIED_TITLE": "Тағйироти Беруна",
    "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span>Берун аз диск тағйир дода шудааст{APP_NAME}<br /><br />Шумо мехоҳед файлро сабт кунед ва онро дар диск тағйир диҳед?",
    "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span>Берун аз диск тағйир дода шудааст{APP_NAME}, аммо баъзе тағйиротҳои сабтнашударо дар {APP_NAME} дорад.Кадоме аз инро шумо истифода бурдан мехоҳед? Мехоҳед сабт кунед?",
    "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span>Берун аз диск тоза карда шудааст{APP_NAME}, аммо  баъзе тағйиротҳои сабтнашударо дар {APP_NAME} дорад.Мехоҳед тағйиротҳоро  сабт кунед?",
    "CONFIRM_FOLDER_DELETE_TITLE": "Тасдиқи хориҷкунӣ",
    "CONFIRM_FOLDER_DELETE": "Ҷузъгирро<span class='dialog-filename'>{0}</span> тоза кардан мехоҳед?",
    "CONFIRM_FILE_DELETE": "Дар ҳақиқат мехоҳед <span class='dialog-filename'>{0}</span> - ро хориҷ кунед?",
    "FILE_DELETED_TITLE": "Файл Тоза Карда Шуд",
    "DONE": "Иҷро шуд",
    "OK": "ОК",
    "CANCEL": "Бекоркунӣ",
    "SAVE_AND_OVERWRITE": "Бознависӣ",
    "DELETE": "Тоза кардан",
    "BUTTON_YES": "Ҳа",
    "BUTTON_NO": "Не",
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Тезтағйирдиҳӣ барои ҷои ҷории курсор мавҷуд нест",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Тезтағйирдиҳӣ: курсорро ба номи ягонаи синф ҷой диҳед",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Тезтағйирдиҳӣ: Атрибути класс нопурра",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Тезтағйирдиҳӣ: Атрибути ID нопурра",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Тезтағйирдиҳӣ: Ҷойгир намудани курсор дар тег, синф ё ки ID",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS функсияи синхронизатсионии тезислоҳкунӣ: Синтаксис нодуруст",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Тезтағйирдиҳӣ:  Курсорро ба  номи функсия гузоред",
    "BUTTON_NEW_RULE": "Қоидаи Нав",
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Дар ҷои ҷории курсор ҳуҷҷат мавҷуд нет ",
    "CMD_FILE_NEW": "Файли Нав",
    "CMD_FILE_NEW_FOLDER": "Ҷузъгири Нав",
    "CMD_FILE_RENAME": "Тағйири ном",
    "CMD_FILE_DELETE": "Нест кардан",
    "CMD_FILE_DOWNLOAD": "Ирсоли файл",
    "CMD_CUT": "Буридан",
    "CMD_COPY": "Нусха",
    "CMD_PASTE": "Гузоштан",
    "CMD_SELECT_ALL": "Интихоби кул",
    "CMD_TOGGLE_QUICK_EDIT": "Тез ислоҳкунӣ",
    "CMD_TOGGLE_QUICK_DOCS": "Ҳуҷҷати тез",
    "DND_MAX_SIZE_EXCEEDED": "ҳаҷми файл набояд аз  ___ Мб зиёд бошад",
    "DND_UNSUPPORTED_FILE_TYPE": "Навъи файл дастгирӣ намекунад",
    "DND_ERROR_UNZIP": "Файл аз архив бардошта нашуд",
    "DND_ERROR_UNTAR": "Файл аз архив бардошта нашуд",
    "DND_SUCCESS_UNZIP_TITLE": "Архивкунӣ бомувафақият иҷро шуд",
    "DND_SUCCESS_UNTAR_TITLE": "Архивкунӣ бомувафақият иҷро шуд",
    "DND_SUCCESS_UNZIP": "Архивкунӣ бомувафақият <b>{0}</b>",
    "DND_SUCCESS_UNTAR": "Архивкунӣ бомувафақият <b>{0}</b>",
    "IMAGE_DIMENSIONS": "{0} (васеъгӣ) &times; {1} (баландӣ) пиксел",
    "IMAGE_FILTERS_TITLE": "Филтри расмҳо",
    "IMAGE_FILTER_PINHOLE": "Гӯшаки сӯзан",
    "IMAGE_FILTER_SEPIA": "Сепия",
    "IMAGE_FILTER_CONTRAST": "Мухолифат",
    "IMAGE_FILTER_VINTAGE": "Кӯҳна",
    "IMAGE_FILTER_SUNRISE": "Субҳдам",
    "IMAGE_FILTER_EMBOSS": "Бардошташуда",
    "IMAGE_FILTER_GLOWING_SUN": "Офтоби пурҷило",
    "IMAGE_SAVE_WITH_FILTERS": "Истифода бурдан",
    "IMAGE_RESET_FILTERS": "Бекоркунӣ",
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Ранги Ҷорӣ",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Ранги Аслӣ",
    "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa Формат",
    "COLOR_EDITOR_HEX_BUTTON_TIP": "Формати Шонздаҳӣ",
    "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa Формат",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0}(вақти истифодашуда{1})",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Вақти истифодашуда {1} )",
    "CMD_JUMPTO_DEFINITION": "Гузаштан ба Муайянкунӣ",
    "CMD_SHOW_PARAMETER_HINT": "Нишон додани нишонаи параметрӣ",
    "NO_ARGUMENTS": "<параметр мавҷуд нест>",
    "DETECTED_EXCLUSION_TITLE": "JavaScript Мушкилӣ барои баровардани файл",
    "CMD_ENABLE_QUICK_VIEW": "Азназаргузаронии тез",
    "DOCS_MORE_LINK": "Бештар хондан",
    "UPLOAD_FILES_DIALOG_HEADER": "Боргузории файл",
    "DRAG_AREA_UPLOAD_FILES_DIALOG_TEXT": "...ё ки файлҳоро ба ин ҷо гиред.",
    "DROP_AREA_UPLOAD_FILES_DIALOG_TEXT": "Хуб, файлҳоро озод намоед! ",
    "UPLOADING_INDICATOR": "Боргузоришуда...",
    "BUTTON_FROM_YOUR_COMPUTER": "Аз компютери шумо...",
    "TAKE_A_SELFIE": "Расми худро бигир...",
    "CMD_MOVE_FILE": "Ҷойивазкуни ба...",
    "PROJECT_ROOT": "Решаи лоиҳа",
    "PICK_A_FOLDER_TO_MOVE_TO": "Интихоби ҷузъгир",
    "ERROR_MOVING_FILE_DIALOG_HEADER": "Хатогӣ ҳангоми ҷойивазкунӣ",
    "UNEXPECTED_ERROR_MOVING_FILE": "Ҳангоми ҷойивазкунӣ хотогӣ шуд, аз нав такрор кунед {0} дар {1}",
    "ERROR_MOVING_FILE_SAME_NAME": "Файл ва ё папка бо ин ном {0} аллакай мавҷуд аст{1}. Номи яке аз онҳоро тағйир диҳед ва давом диҳед.",
    "CONSOLE_TITLE": "Консол",
    "CONSOLE_TOOLTIP": "Кушодани JavaScript Console",
    "CONSOLE_CLEAR": "Тозакунӣ",
    "CONSOLE_CLEAR_TOOLTIP": "Тозакунии Console",
    "CONSOLE_CLOSE_TOOLTIP": "Пӯшидани Console",
    "CONSOLE_EMPTY_STRING": "Сатри холӣ",
    "CONSOLE_HELPTEXT": "Бо истифодаи консол  <code>console.log(&quot;Hello World!&quot;);</code>- ро ба файли  JavaScript ҳамроҳ кунед."
});
